# Generated by Django 5.1.5 on 2025-02-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_and_orders', '0003_alter_offer_creator_alter_offerdetail_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
