# Generated by Django 5.1.5 on 2025-02-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_and_orders', '0007_alter_offer_created_at_alter_offer_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='creator',
            new_name='user',
        ),
    ]
