# Generated by Django 5.1.5 on 2025-02-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_and_orders', '0009_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'IN_PROGRESS'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED')], default='in_progress', max_length=20),
        ),
    ]
