# Generated by Django 5.1.5 on 2025-02-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_and_orders', '0011_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.FileField(null=True, upload_to='offer_pictures'),
        ),
    ]
