# Generated by Django 5.1.5 on 2025-02-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_and_orders', '0012_alter_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='offer_pictures'),
        ),
    ]
