# Generated by Django 5.1.5 on 2025-01-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_userprofile_created_at_userprofile_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
